### ISSUE TITLE
运行一段时间总是会报错，IP更新不了，不知是什么原因引起的

### ISSUE THREAD

**Issue by pilotcy** [Charles94jp/NameSilo-DDNS#20]
Traceback (most recent call last):
  File "/home/NameSilo-DDNS/lib/current_ip.py", line 40, in fetch
    r = self._http_client.get('https://api-v3.speedtest.cn/ip')
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1039, in get
    return self.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 815, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 902, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 930, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 967, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1003, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 104] Connection reset by peer

**Comment by Charles94jp** [comment]
日志里有current_ip.py的报错是正常的，可能是网络不好。
IP更新不了我没遇到，可以配置自动重启。配置邮箱接收信息会更好。
