### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by nxydyxsj123456** [Charles94jp/NameSilo-DDNS#25]
2023-07-20 14:29:40,616 - CurrentIP.fetch[line:71] - ERROR: 	error code: count=2
2023-07-20 14:29:43,174 - CurrentIP.fetch[line:76] - INFO: 	current host ip: 222.205.75.76
2023-07-20 14:29:43,174 - DDNS.start[line:202] - ERROR: 'domain_ip'
Traceback (most recent call last):
  File "/home/NameSilo-DDNS/ddns.py", line 186, in start
    if (enable_ipv4 and not self._namesilo_client.ip_equal(current_ip)) or \
  File "/home/NameSilo-DDNS/lib/namesilo_client.py", line 198, in ip_equal
    result = result & (ip == domain['domain_ip'])
KeyError: 'domain_ip'

**Comment by Charles94jp** [comment]
信息太少了，看起来是配置文件没填写对或者没加载上。看看你的配置文件`conf/conf.json`， 替换、脱敏key、域名等敏感信息再发上来。

**Comment by yacper** [comment]
same problem

**Comment by yacper** [comment]
> 

是apikey的问题，namesilo存在两个生成apikey的页面，老的页面生成的apikey现在无法使用了，新的是：
https://www.namesilo.com/account/api-manager

**Comment by yacper** [comment]
> > 
> 
> 是apikey的问题，namesilo存在两个生成apikey的页面，老的页面生成的apikey现在无法使用了，新的是： https://www.namesilo.com/account/api-manager

可以通过：
https://www.namesilo.com/api/dnsListRecords?version=1&type=xml&key=[your api key]&domain=[domain], 先确认apikey是对的在运行脚本
