### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by T888T** [Charles94jp/NameSilo-DDNS#26]
```python
2023-07-31 02:17:55,044 - CurrentIP.fetch_v6[line:107] - ERROR: [Errno 101] Network unreachable
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpcore/backends/sync.py", line 94, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/httpcore/backends/sync.py", line 94, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [Errno 101] Network unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/NameSilo-DDNS/lib/current_ip.py", line 92, in fetch_v6
    r = self._http_client.get('http://test6.ustc.edu.cn/backend/getIP.php')
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1045, in get
    return self.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 908, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 101] Network unreachable
2023-07-31 02:17:55,056 - CurrentIP.fetch_v6[line:109] - ERROR: 	error code: count=0
2023-07-31 02:17:58,788 - CurrentIP.fetch_v6[line:109] - ERROR: 	error code: count=1
```

**Comment by Charles94jp** [comment]
一般来说`CurrentIP.fetch`有报错正常，因为网络不稳定，设计时有容错，连续多次报错程序才会异常停止。

当然你这个可能是路由器ipv6没配置好，无法访问ipv6地址，你可以试试浏览器打开`test6.ustc.edu.cn`.

或者`curl http://test6.ustc.edu.cn/backend/getIP.php`，看看你的ipv6能用了没。

**Comment by T888T** [comment]
> 
ipv6是可以访问的，但还是一直在报错，大概挂了有一个小时了没有一次是成功的，使用的docker

**Comment by Charles94jp** [comment]
试试`docker exec -it ddns /bin/sh`进入docker的命令行，运行：

```
wget -q -O - http://test6.ustc.edu.cn/backend/getIP.php
```

看看docker能不能访问ipv6🤣 程序我这边是运行正常的。你的是x86处理器吧，不是arm吧？

**Comment by T888T** [comment]
> 试试`docker exec -it ddns /bin/sh`进入docker的命令行，运行：
> 
> ```
> wget -q -O - http://test6.ustc.edu.cn/backend/getIP.php
> ```
> 
> 看看docker能不能访问ipv6🤣 程序我这边是运行正常的。你的是x86处理器吧，不是arm吧？
运行结果，貌似是连接不上，请问如何开启docker的ipv6呢，宿主机是可以使用的
/ # wget -q -O - http://test6.ustc.edu.cn/backend/getIP.php
wget: can't connect to remote host: Network unreachable
使用的是docker for windows 是x86
