### ISSUE TITLE
docker部署后报错,同样的配置文件(只改了域名)在不同的机子上一个能运行另一个不行

### ISSUE THREAD

**Issue by wanduwang** [Charles94jp/NameSilo-DDNS#35]
我又来了(
在解决了IP问题后我的一台N5105安装winserver2022的机子能够正常运行,而另一台i3-10100T的win10专业版报错如下
两台机子均使用docker进行运行
2023-10-23 23:25:19,706 - DDNS.__init__[line:91] - INFO: 

 ███╗   ██╗  █████╗  ███╗   ███╗ ███████╗ ███████╗ ██╗ ██╗       ██████╗      ██████╗  ██████╗  ███╗   ██╗ ███████╗
 ████╗  ██║ ██╔══██╗ ████╗ ████║ ██╔════╝ ██╔════╝ ██║ ██║      ██╔═══██╗     ██╔══██╗ ██╔══██╗ ████╗  ██║ ██╔════╝
 ██╔██╗ ██║ ███████║ ██╔████╔██║ █████╗   ███████╗ ██║ ██║      ██║   ██║     ██║  ██║ ██║  ██║ ██╔██╗ ██║ ███████╗
 ██║╚██╗██║ ██╔══██║ ██║╚██╔╝██║ ██╔══╝   ╚════██║ ██║ ██║      ██║   ██║     ██║  ██║ ██║  ██║ ██║╚██╗██║ ╚════██║
 ██║ ╚████║ ██║  ██║ ██║ ╚═╝ ██║ ███████╗ ███████║ ██║ ███████╗ ╚██████╔╝     ██████╔╝ ██████╔╝ ██║ ╚████║ ███████║
 ╚═╝  ╚═══╝ ╚═╝  ╚═╝ ╚═╝     ╚═╝ ╚══════╝ ╚══════╝ ╚═╝ ╚══════╝  ╚═════╝      ╚═════╝  ╚═════╝  ╚═╝  ╚═══╝ ╚══════╝
 
2023-10-23 23:25:24,713 - NameSiloClient._list_dns_api[line:127] - ERROR: 	Error, process stopped. It could be due to the configuration file error, or the NameSilo server error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 212, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.9/socket.py", line 823, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 262, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 219, in connect_tcp
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/NameSilo-DDNS/ddns.py", line 247, in <module>
    main()
  File "/home/NameSilo-DDNS/ddns.py", line 243, in main
    ddns.start()
  File "/home/NameSilo-DDNS/ddns.py", line 172, in start
    self._namesilo_client.fetch_domains_info()
  File "/home/NameSilo-DDNS/lib/namesilo_client.py", line 83, in fetch_domains_info
    self._list_dns_api(domain, cache, t='A')
  File "/home/NameSilo-DDNS/lib/namesilo_client.py", line 98, in _list_dns_api
    ro = self._http_client.get(url)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1041, in get
    return self.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Try again

配置文件我是复制粘贴的,只进去改了个域名,请求大佬解惑,PS,报错的机器上IPV6有小问题(流量只进不出),但是我根本没配置IPV6域名

**Comment by Charles94jp** [comment]
看起来是你网络不行，连接不到NameSilo服务器

试试在机器上运行

```bash
wget -O - 'https://www.namesilo.com/api/dnsListRecords?version=1&type=xml&key=11'
```

看能否连接NameSilo
