### ISSUE TITLE
Exception: Response error or configuration file error

### ISSUE THREAD

**Issue by sagaciousGenius** [Charles94jp/NameSilo-DDNS#38]
我根据 READEME 文件第六步，我把项目直接克隆到本地，使用命令 python ddns.py 报错了
PS G:\LearnArckives\doByHand\ddns\name-silo\NameSilo-DDNS> ls

    目录: G:\LearnArckives\doByHand\ddns\name-silo\NameSilo-DDNS

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2024/3/16     22:53                conf
d-----         2024/3/16     21:32                docker
d-----         2024/3/16     23:19                lib
d-----         2024/3/16     23:21                log
d-----         2024/3/16     21:32                win
-a----         2024/3/16     23:56            216 -
-a----         2024/3/16     21:32             55 .gitignore
-a----         2024/3/16     21:32           2405 DDNS
-a----         2024/3/16     21:32          12950 ddns.py
-a----         2024/3/16     21:32            301 DDNS.service
-a----         2024/3/16     21:32            520 Dockerfile
-a----         2024/3/16     21:32         440401 example.png
-a----         2024/3/16     21:32           1087 LICENSE
-a----         2024/3/16     21:32          19012 logo.svg
-a----         2024/3/16     21:32         180431 Network-topology-en.png
-a----         2024/3/16     21:32          17967 readme.en-us.md
-a----         2024/3/16     21:32          14439 readme.md

====================================================================================
PS G:\LearnArckives\doByHand\ddns\name-silo\NameSilo-DDNS> python ddns.py
G:\LearnArckives\doByHand\ddns\name-silo\NameSilo-DDNS\ddns.py:68: DeprecationWarning: ssl.OP_NO_SSL*/ssl.OP_NO_TLS* options are deprecated
  _SSL_CONTEXT.options ^= ssl.OP_NO_TLSv1
Traceback (most recent call last):
  File "G:\LearnArckives\doByHand\ddns\name-silo\NameSilo-DDNS\ddns.py", line 247, in <module>
    main()
  File "G:\LearnArckives\doByHand\ddns\name-silo\NameSilo-DDNS\ddns.py", line 243, in main
    ddns.start()
  File "G:\LearnArckives\doByHand\ddns\name-silo\NameSilo-DDNS\ddns.py", line 172, in start
    self._namesilo_client.fetch_domains_info()
  File "G:\LearnArckives\doByHand\ddns\name-silo\NameSilo-DDNS\lib\namesilo_client.py", line 85, in fetch_domains_info
    self._list_dns_api(domain, cache, t='A')
  File "G:\LearnArckives\doByHand\ddns\name-silo\NameSilo-DDNS\lib\namesilo_client.py", line 118, in _list_dns_api
    raise Exception("Response error or configuration file error")
Exception: Response error or configuration file error
====================================================================================
然后调试发现这个
![image](https://github.com/Charles94jp/NameSilo-DDNS/assets/98566292/8927fdd7-cb90-482b-b553-01db063c5ff6)

httpx.ConnectError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
===================================================================================
这个问题怎么解决

**Comment by sagaciousGenius** [comment]
手机上的 Termux 可以用，但是到电脑上就不行

**Comment by Charles94jp** [comment]
配置文件错误，或者你电脑上有挂代理

**Comment by sagaciousGenius** [comment]
![image](https://github.com/Charles94jp/NameSilo-DDNS/assets/98566292/67ae9115-151a-4465-8af8-85a3e1a6828d)
配置是这样，你帮忙看看哪里有错
