### ISSUE TITLE
随机出现SSL错误导致程序卡住

### ISSUE THREAD

**Issue by MarvinChiang** [Charles94jp/NameSilo-DDNS#6]
目前我的解决方法是把**./NameSilo-DDNS/DDNS restart**做成定时任务
经常在日志中会各种出现SSL出错情况，类似
```
Traceback (most recent call last):
  File "ddns.py", line 100, in __init__
    r = httpx.get("https://www.ip138.com/", headers=self.httpHeaders, timeout=10)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_api.py", line 189, in get
    return request(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_api.py", line 100, in request
    return client.request(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 802, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 889, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 917, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 954, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 990, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:1131)
```

**Comment by Charles94jp** [comment]
针对程序出现**各种SSL错误**的情况：
1. 如你举例中的`File "ddns.py", line 100`，这个是程序初始化时才会访问 https://www.ip138.com 。如果这里报错，**说明程序没启动成功**，程序启动几次。后续会考虑优化一下这里
2. 获取本机IP时的ssl报错我已经优化过，不会卡住程序运行
3. 当IP发生变动时，程序向NameSilo提交新IP时，会出现SSL错误导致程序停止，我也遇到过很多次。解决办法是[配置auto_restart选项](https://github.com/Charles94jp/NameSilo-DDNS/blob/python/readme.zh-CN.md#configuration)，程序会自动重启

**Comment by Charles94jp** [comment]
已经解决了，原因是httpx库默认不支持低版本的TLS 1.0协议
程序v2.1.0是一个稳定的版本，新版本正在筹划支持ipv6
